"""Generate Rimbun's original ornament SVGs into ../assets/svg/ (deterministic, no external art).

    python templates/rimbun/art/build_art.py
    python tools/recolor_svg.py templates/rimbun      # then regenerate variant sets

Motifs: monstera, banana leaf (daun pisang), fern (pakis), frangipani cluster (kamboja),
woven rattan ring (rotan), falling dry leaf (daun), sprig divider. Leaf greens sit in hue 120-175
so variant recolor rules can move them; rattan / flowers / dry leaf stay warm.
"""
import math
import random
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "assets" / "svg"
HEAD = '<!-- Rimbun ornament, (c) WAT Wedding Invitation. Generated by art/build_art.py -->\n'


def f(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")


def poly(points, close=True):
    d = "M" + " L".join(f"{f(x)},{f(y)}" for x, y in points)
    return d + (" Z" if close else "")


def svg(w, h, body, defs=""):
    return (HEAD + f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">'
            + (f"<defs>{defs}</defs>" if defs else "") + body + "</svg>\n")


# ---------------------------------------------------------------- monstera
def monstera():
    cx, cy, a, b = 200, 230, 172, 200
    notch_side = [0.95, 1.32, 1.7, 2.08, 2.46]
    notches = notch_side + [2 * math.pi - x for x in notch_side]

    def edge(p):
        d = min(p, 2 * math.pi - p)
        k = 1 - 0.36 * math.exp(-(d / 0.32) ** 2) + 0.07 * math.exp(-((p - math.pi) / 0.45) ** 2)
        return cx + a * math.sin(p) * k, cy + b * math.cos(p) * k

    def mid_y(y):
        return max(cy - b * 0.9, min(cy + b * 0.55, y))

    pts, p, step = [], 0.05, 0.025
    while p < 2 * math.pi - 0.05:
        hit = next((n for n in notches if abs(p - n) < step / 2), None)
        if hit is not None:
            e0, e1 = edge(hit - 0.03), edge(hit + 0.03)
            ex, ey = edge(hit)
            depth = 0.58 + 0.08 * math.sin(hit * 3)
            ix, iy = ex + (cx - ex) * depth, ey + (mid_y(ey + 18) - ey) * depth
            pts += [e0, (ix, iy), e1]
        else:
            pts.append(edge(p))
        p += step
    leaf = poly(pts)
    veins = "".join(
        f'<path d="M{f(cx)},{f(mid_y(edge(n)[1] + 30))} Q{f((cx + edge(n)[0]) / 2)},{f(edge(n)[1] + 12)} {f(edge(n)[0] * .9 + cx * .1)},{f(edge(n)[1] * .9 + cy * .1)}" />'
        for n in [(notches[i] + notches[i + 1]) / 2 for i in range(len(notch_side) - 1)]
        + [(notches[i] + notches[i + 1]) / 2 for i in range(len(notch_side), len(notches) - 1)])
    holes = "".join(
        f'<ellipse cx="{f(cx + s * dx)}" cy="{f(y)}" rx="{f(rx)}" ry="7" transform="rotate({f(s * 28)} {f(cx + s * dx)} {f(y)})" fill="#000"/>'
        for s in (-1, 1) for dx, y, rx in ((42, 150, 15), (48, 225, 17), (40, 298, 13)))
    defs = ('<linearGradient id="mg" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="#1d5a44"/><stop offset=".55" stop-color="#2f7a57"/><stop offset="1" stop-color="#58a57a"/></linearGradient>'
            f'<mask id="mh"><rect width="400" height="480" fill="#fff"/>{holes}</mask>')
    body = (f'<path d="M{cx},470 C{cx - 4},420 {cx},380 {cx},{f(cy + b * .55)}" stroke="#1f5a40" stroke-width="7" fill="none" stroke-linecap="round"/>'
            f'<g mask="url(#mh)"><path d="{leaf}" fill="url(#mg)"/>'
            f'<path d="M{cx},{f(cy + b * .55)} L{cx},{f(cy - b * .88)}" stroke="#174534" stroke-width="4" opacity=".7" fill="none"/>'
            f'<g stroke="#174534" stroke-width="2.2" opacity=".45" fill="none">{veins}</g></g>')
    return svg(400, 480, body, defs)


# ---------------------------------------------------------------- banana leaf
def pisang():
    L, cx = 540, 110
    rng = random.Random(7)
    tears = {0.34: 0.8, 0.52: 0.65, 0.7: 0.9}  # t -> depth (fraction of half width), right side
    left, right = [], []
    n = 90
    for i in range(n + 1):
        t = i / n
        y = 560 - 20 - t * L
        x = cx + 18 * math.sin(t * 2.2)
        w = 92 * (math.sin(math.pi * min(t * 1.02, 1)) ** 0.55) * (1 - 0.15 * t)
        left.append((x - w, y))
        tear = next((d for tt, d in tears.items() if abs(t - tt) < 0.5 / n), None)
        if tear:
            right += [(x + w, y + 4), (x + w * (1 - tear), y - w * tear * 0.55), (x + w, y - 2)]
        else:
            right.append((x + w, y))
    outline = poly(left + right[::-1])
    mid = [(cx + 18 * math.sin(t / 30 * 2.2), 540 - t / 30 * L) for t in range(31)]
    veins = []
    for i in range(3, 58):
        t = i / 60
        y = 540 - t * L
        x = cx + 18 * math.sin(t * 2.2)
        w = 92 * (math.sin(math.pi * t) ** 0.55) * (1 - 0.15 * t) * 0.92
        for s in (-1, 1):
            veins.append(f"M{f(x)},{f(y)} L{f(x + s * w)},{f(y - w * 0.55)}")
    defs = '<linearGradient id="pg" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#2a6e4d"/><stop offset=".5" stop-color="#3f8c61"/><stop offset="1" stop-color="#6bb488"/></linearGradient>'
    body = (f'<path d="{outline}" fill="url(#pg)"/>'
            f'<path d="{" ".join(veins)}" stroke="#1d5a40" stroke-width="1" opacity=".35" fill="none"/>'
            f'<path d="{poly(mid, False)}" stroke="#d9e3b3" stroke-width="5" opacity=".75" fill="none" stroke-linecap="round"/>')
    return svg(260, 560, body, defs)


# ---------------------------------------------------------------- fern
def pakis():
    def curve(t):  # quadratic bezier rachis
        p0, p1, p2 = (50, 470), (70, 180), (250, 40)
        x = (1 - t) ** 2 * p0[0] + 2 * (1 - t) * t * p1[0] + t * t * p2[0]
        y = (1 - t) ** 2 * p0[1] + 2 * (1 - t) * t * p1[1] + t * t * p2[1]
        dx = 2 * (1 - t) * (p1[0] - p0[0]) + 2 * t * (p2[0] - p1[0])
        dy = 2 * (1 - t) * (p1[1] - p0[1]) + 2 * t * (p2[1] - p1[1])
        return x, y, math.degrees(math.atan2(dy, dx))

    greens = ["#2e7d55", "#378a5f", "#44966a", "#52a476"]
    leaflets = []
    for i in range(26):
        t = 0.08 + i * 0.034
        x, y, ang = curve(t)
        size = 52 * (1 - t) ** 0.8 + 8
        for s, off in ((1, 62), (-1, -62)):
            a = ang + off
            lx, ly = x + math.cos(math.radians(a)) * size * 0.55, y + math.sin(math.radians(a)) * size * 0.55
            leaflets.append(f'<ellipse cx="{f(lx)}" cy="{f(ly)}" rx="{f(size * .58)}" ry="{f(size * .17)}" transform="rotate({f(a)} {f(lx)} {f(ly)})" fill="{greens[i % 4]}"/>')
    rach = poly([curve(i / 40)[:2] for i in range(41)], False)
    body = f'<path d="{rach}" stroke="#23603f" stroke-width="4" fill="none" stroke-linecap="round"/>{"".join(leaflets)}'
    return svg(300, 480, body)


# ---------------------------------------------------------------- frangipani cluster
def petal_path(cx, cy, r, ang):
    a = math.radians(ang)
    tip = (cx + math.cos(a) * r, cy + math.sin(a) * r)
    c1 = (cx + math.cos(a - 0.9) * r * 0.9, cy + math.sin(a - 0.9) * r * 0.9)
    c2 = (cx + math.cos(a + 0.35) * r * 1.15, cy + math.sin(a + 0.35) * r * 1.15)
    return f"M{f(cx)},{f(cy)} Q{f(c1[0])},{f(c1[1])} {f(tip[0])},{f(tip[1])} Q{f(c2[0])},{f(c2[1])} {f(cx)},{f(cy)} Z"


def kamboja():
    flowers = [(120, 150, 58, -20), (218, 118, 50, 15), (205, 205, 44, 40)]
    leaves = ['<path d="M150,190 C60,215 20,250 8,272 C70,262 130,238 170,200 Z" fill="#2f6b4a"/>',
              '<path d="M200,170 C290,185 330,230 352,262 C290,250 230,220 190,185 Z" fill="#3b7d56"/>',
              '<path d="M60,262 C80,245 110,228 150,205" stroke="#1f4d35" stroke-width="2" fill="none" opacity=".6"/>',
              '<path d="M340,255 C300,228 260,205 205,182" stroke="#1f4d35" stroke-width="2" fill="none" opacity=".6"/>']
    fl = []
    for cx, cy, r, rot in flowers:
        fl += [f'<path d="{petal_path(cx, cy, r, rot + k * 72)}" fill="url(#kp)" stroke="#e7dcc4" stroke-width="1"/>' for k in range(5)]
        fl.append(f'<circle cx="{cx}" cy="{cy}" r="{f(r * .16)}" fill="#e9b23a"/>')
    defs = '<radialGradient id="kp" cx=".2" cy=".2" r="1"><stop offset="0" stop-color="#f2c44e"/><stop offset=".28" stop-color="#fbf1d8"/><stop offset="1" stop-color="#fffdf7"/></radialGradient>'
    return svg(360, 280, "".join(leaves) + "".join(fl), defs)


# ---------------------------------------------------------------- woven rattan ring
def rotan():
    c, ro, ri = 210, 200, 156
    rm = (ro + ri) / 2
    parts = [f'<circle cx="{c}" cy="{c}" r="{rm}" fill="none" stroke="#b5874f" stroke-width="{ro - ri}"/>']
    n = 44
    for k in range(n):
        a = 360 / n * k
        tilt = 32 if k % 2 else -32
        x = c + math.cos(math.radians(a)) * rm
        y = c + math.sin(math.radians(a)) * rm
        parts.append(f'<rect x="{f(x - 7)}" y="{f(y - 25)}" width="14" height="50" rx="7" fill="url(#rg{k % 2})" '
                     f'transform="rotate({f(a + 90 + tilt)} {f(x)} {f(y)})"/>')
    parts += [f'<circle cx="{c}" cy="{c}" r="{ro}" fill="none" stroke="#7d5a2e" stroke-width="3"/>',
              f'<circle cx="{c}" cy="{c}" r="{ri}" fill="none" stroke="#7d5a2e" stroke-width="3"/>',
              f'<circle cx="{c}" cy="{c}" r="{ri - 8}" fill="none" stroke="#c9a06a" stroke-width="1.5" stroke-dasharray="2 7" stroke-linecap="round"/>']
    defs = ('<linearGradient id="rg0" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#9c7040"/><stop offset=".5" stop-color="#e2bd86"/><stop offset="1" stop-color="#a87a45"/></linearGradient>'
            '<linearGradient id="rg1" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#8a6034"/><stop offset=".5" stop-color="#d3aa70"/><stop offset="1" stop-color="#946839"/></linearGradient>')
    return svg(420, 420, "".join(parts), defs)


# ---------------------------------------------------------------- dry leaf particle
def daun():
    body = ('<path d="M20,2 C33,10 36,26 20,38 C4,26 7,10 20,2 Z" fill="#c9974f"/>'
            '<path d="M20,4 L20,37 M20,14 L28,10 M20,21 L30,17 M20,28 L27,25 M20,14 L12,10 M20,21 L10,17 M20,28 L13,25" stroke="#8c6130" stroke-width="1.2" fill="none" opacity=".7"/>')
    return svg(40, 40, body)


# ---------------------------------------------------------------- divider sprig
def divider():
    leaves = []
    for i, x in enumerate(range(30, 140, 22)):
        s = 1 if i % 2 else -1
        leaves.append(f'<ellipse cx="{x}" cy="{20 + s * 6}" rx="11" ry="4.2" transform="rotate({s * 28} {x} {20 + s * 6})" fill="#3f8c61"/>')
        leaves.append(f'<ellipse cx="{320 - x}" cy="{20 + s * 6}" rx="11" ry="4.2" transform="rotate({-s * 28} {320 - x} {20 + s * 6})" fill="#3f8c61"/>')
    center = "".join(f'<path d="{petal_path(160, 20, 13, k * 72 - 90)}" fill="#fbf1d8" stroke="#d8c8a8" stroke-width=".8"/>' for k in range(5))
    body = (f'<path d="M14,20 L306,20" stroke="#2f6b4a" stroke-width="1.6" stroke-linecap="round"/>{"".join(leaves)}'
            f'{center}<circle cx="160" cy="20" r="2.6" fill="#e9b23a"/>')
    return svg(320, 40, body)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    art = {"monstera.svg": monstera(), "pisang.svg": pisang(), "pakis.svg": pakis(), "kamboja.svg": kamboja(),
           "rotan.svg": rotan(), "daun.svg": daun(), "divider.svg": divider()}
    for name, text in art.items():
        (OUT / name).write_text(text, encoding="utf-8")
        print(f"{name}: {len(text) // 1024 + 1} kB")


if __name__ == "__main__":
    main()
